name = "meishi-web"
main = "worker/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

assets = { directory = "dist/client", binding = "ASSETS" }

routes = [
  { pattern = "dashboard.ekagu.qzz.io/*", zone_id = "ba7addf8cd2b762faf687c98b2053f2c" }
]

[[d1_databases]]
binding = "DB"
database_name = "meishi-db"
database_id = "0a387f70-533d-4aa4-9c15-fef532d1f226"
migrations_dir = "drizzle/migrations"
